### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by trymeouteh** [yaxarat/lingvaandroid#1]
Please punish this app on F-Droid and maintain it with updates.

**Comment by yaxarat** [comment]
I am working on getting this up to  F-Droid once the current batch of feature updates I am working on ends. But depending on time, I might upload to F-Droid first.

**Comment by CodeCubeNeo** [comment]
Hello! I would also like to join the petition for getting this app on fdroid :). I think it would be discovered by more people + easier to install

**Comment by yaxarat** [comment]
Update: FDroid intake request has been filed: https://gitlab.com/fdroid/rfp/-/issues/2033

**Comment by IzzySoft** [comment]
Ooops: that RFP "went into hiding" as the bot failed due to "too-many-git-urls" (didn't know which one to follow) and we missed it, apologies! I've redacted your initial post there and triggered the bot again. Hopefully we'll have more success this time.

**Comment by IzzySoft** [comment]
OK, the bot succeeded this time. It asks for [Fastlane structure](https://gitlab.com/-/snippets/1895688) in your repo here; could you establish that? For starters, just the `short_description.txt` (aka "summary", max 80 chars) and the `full_description.txt` for `en-US` would suffice, though I'd strongly recommend to also include an icon and some screenshots.

Going by your Playstore presence, `short_description.txt` could be

```
Privacy focused open source translator
```

and `full_description.txt`

```
An Android client for the Lingala Translator. <a href='https://github.com/TheDavidDelta/lingva-translate'>Lingva translator</a> is an open-source translator with over a hundred languages available.
```

And if you'd move the screenshots from the readme to `fastlane/metadata/android/en-US/images/phoneScreenshots`, that part would be covered as well :smiley:

Just let us know when everything is in place and we'll have another look. Thanks @yaxarat!

**Comment by IzzySoft** [comment]
A month has passed, so a friendl reminder: Any chance to get Fastlane established?

**Comment by yaxarat** [comment]
@IzzySoft Sorry! Had a personal conflict going on for a while. I will get this set up this week. Thank you for the reminder 🙇🏼

**Comment by IzzySoft** [comment]
First things first, of course! Best progress then on both ends :crossed_fingers:

**Comment by yaxarat** [comment]
@IzzySoft thank you again for the detailed guide on setting up the fastlane structure. I've set it up now (I think). Please let me know what the next steps are. Thank you!

**Comment by IzzySoft** [comment]
Fastlane structure looks good, thanks! You might consider adding an icon, too (can be the `ic_launcher_playstore.png` you're already using) to make sure there is one shown with the listings – especially as your app otherwise uses XML icons (which often cause issues with F-Droid listings).

That done, you should start [tagging releases](https://github.com/yaxarat/lingvaandroid/tags) (using `git tag` and `git push --tags`), so F-Droid knows which commits it shall pick up. For tag names, best practices include options like `v<versionName>` or `c<versionCode>` (the prefixed letter is just to make sure it's considered a string) – so the current one would be either `v1.2.1` or `c12`.

**Comment by yaxarat** [comment]
Sounds good. I will make those updated with my upcoming release and tag them accordingly. Is there anything else I need to do on the gitlab/Froid request for packaging side to complete this process? Thanks!

**Comment by IzzySoft** [comment]
If you let us know when the above has been implemented, we can trigger the bot again to see what it has to say. Then we go by the results concerning the next steps (which, if all engines are green, would be creating the YAML metadata file and providing it to fdroiddata via a merge request, where it runs through some more checks then).

**Comment by yaxarat** [comment]
@IzzySoft - I've released a v1.2.2 version of the app. It is [tagged and is on a release branch](https://github.com/yaxarat/lingvaandroid/tree/release-1.2.2).

**Comment by IzzySoft** [comment]
Thanks! Rescan triggered.

**Comment by yaxarat** [comment]
For those who are tracking the status: https://gitlab.com/fdroid/rfp/-/issues/2033#note_856508777

**Comment by yaxarat** [comment]
Lentil translate is now on the Fdroid as of the 1.2.4 release!
