### ISSUE TITLE
Add option popup to translate

### ISSUE THREAD

**Issue by clementwzk** [yaxarat/lingvaandroid#10]
It would be awesome if you add an option like Google Translate do to translate any text with a popup

Screenshot of the feature :

![Screenshot_20220724-021751](https://user-images.githubusercontent.com/50015928/180627096-afc8c103-f929-43be-a7ad-0b64c5d6fdc2.png)
![Screenshot_20220724-021759](https://user-images.githubusercontent.com/50015928/180627097-5736794e-c6c5-4641-ab18-e81c34291303.png)

**Comment by yaxarat** [comment]
That's a cool feature! I've never implemented something like this, so it may take a while. But it is definitely on the horizon.

**Comment by BahrawiElimi** [comment]
@yaxarat This feature is implemented in deepl you can look at the code and integrate it into Lentil Translate
Source:
https://github.com/sakusaku3939/DeepLAndroid

**Comment by yaxarat** [comment]
Thanks for the info! I am hoping to get this in with the next release 🤞🏼
