### ISSUE TITLE
Detect language

### ISSUE THREAD

**Issue by Gottarocket** [yaxarat/lingvaandroid#17]
It works good but better if it can show whats the detected langauge. Since many languages use English letters and if we dont know any word from that langauge, it would be helpful to show the detected langauge next to source text

**Comment by yaxarat** [comment]
Great idea! A new release will be coming out in a week or so. I will make sure to include this feature :)

**Comment by yaxarat** [comment]
Part of 1.2.3 release. It now auto-picks detected language as a source. Let me know what you think.
