### ISSUE TITLE
Error Occurred

### ISSUE THREAD

**Issue by BahrawiElimi** [yaxarat/lingvaandroid#21]
When trying to translate some texts, it gives the result of Error Occurred, while the same texts are translated in https://lingva.ml without a problem.
For example, this text:
> Autorun Manager is an super tool that lets you can disable or remove autorun components of an app. Generally, an app can be automatically started when it declared some receivers(one type of components in android app) that listen on some events like boot completed, application installed, connectivity changed, etc.
The Declaration looks like:
It means that when the boot completed or an application installed, the component of com.xx.xx will be started.
Based on above knowledge, it's easy to understand the analysis page(It is opened by clicking at an app):
The tool provides 3 methods to disable auto run:
Disable the autorun receiver component. (Your device must be rooted)
Disable the whole app. For rarely used apps, you could try this option. You could enable and launch it in "Disabled Apps" by long clicking at the app. (Your device must be rooted too)
Remove events that bring the receiver to run. (ROOT is not needed, but only available for User apps which is installed by yourself, and need re-installation)
You could switch the root mode and non-root mode in the setting page.
It also provides 2 usage scenarios:
Click on "Running Apps", and then kill the app you don't want to run by long clicking at the app and then select 'Kill' menu. Wait for a moment(For example, 1 minites), and refresh the running app list. If it appears again, click at the app to see why it can be automatically started, and disable or remove related components/events. (Please note the kill function provided by this tool can not completely kill the app, you can try 'Force Stop' in application info page)
Click on "Autorun Apps", it will enable us to search autorun apps grouped by certain events. And in searching result page, we can simplely disable the autorun components by long clicking at an app and select 'Disable' menu. (Please note that in some other tools, the autorun apps usually means apps triggered by 'After Start' event in this tool)
I've tried to make this tool as simple/green as possible(no services, no receivers, except the AD in the free version), please click at 'Exit' button to completely close it.

Screenshots:
![Screenshot_2022-10-05-16-22-42-81](https://user-images.githubusercontent.com/61330601/194087296-c74c53ed-7fb8-4b36-9a68-5d0ee06bc893.jpg)
![Screenshot_2022-10-05-16-22-15-20](https://user-images.githubusercontent.com/61330601/194087359-a3821f99-6d49-4b38-9e90-0cc2ab05e208.jpg)

**Comment by BahrawiElimi** [comment]
This text is also for describing the issue when trying to translate it:
> When trying to translate some texts, it gives the result of Error Occurred, while the same texts are translated in https://lingva.ml without a problem.
For example, this text:
![Screenshot_2022-10-05-16-39-15-56](https://user-images.githubusercontent.com/61330601/194089655-b5d7712a-736e-4773-b5ff-840a7f617388.jpg)

**Comment by yaxarat** [comment]
Thank you for the report! I will take a look at this later today.
