### ISSUE TITLE
Not possible to linebreak

### ISSUE THREAD

**Issue by AlphaElwedritsch** [yaxarat/lingvaandroid#24]
it is not possible to insert a line break. Enter key acts as "start translation".

**Comment by AlphaElwedritsch** [comment]
Hi, 
Is the problem understandable?
Will there be a fix?
It is essential that you can also break the line when entering text.
thx

**Comment by yaxarat** [comment]
Yes! The fix for this issue will be in the next release. There are a bunch of big changes coming so I am making sure nothing breaks with the next release.
