### ISSUE TITLE
Quick access to translate when marking text

### ISSUE THREAD

**Issue by Terkyz** [yaxarat/lingvaandroid#25]
Within Firefox, if I highlight a text to copy it, several quick options appear to quickly access an app and fulfill a function, such as with Notesnook, which allows me to quickly create a note, it is possible to create a function like this to quickly translate text in Lentil?

**Comment by yaxarat** [comment]
I sure can, and it will be a part of the next release. Closing the issue though since this seems to be a repeat of #10
