### ISSUE TITLE
Changing the lingva instance

### ISSUE THREAD

**Issue by AlexMeier99** [yaxarat/lingvaandroid#3]
Hi @yaxarat
one more feeature request: I'd love being able to switch the [instance](https://github.com/TheDavidDelta/lingva-translate/blob/main/instances.json)  used.

The following workflow might work for you:

1. Fetch  [instances.json](https://github.com/TheDavidDelta/lingva-translate/blob/main/instances.json)
2. Parse json
3. Fill the data into a [`spinner`](https://developer.android.com/guide/topics/ui/controls/spinner) in the [`SettingsBottomSheet`](https://github.com/yaxarat/lingvaandroid/blob/main/app/src/main/java/dev/atajan/lingva_android/ui/screens/TranslateScreen.kt#L195)
4. Save user selection in the viewmodel

I'd be very grateful if you could integrate this.

Regards,
Alexei

**Comment by yaxarat** [comment]
Hi @AlexMeier99. Thanks for the suggestion. I haven't personally tried, but is there a translation result difference between these instances? The app currently only changes instances when the endpoint is down for some reason. Just want to know the use case.

**Comment by AlexMeier99** [comment]
Well my personal use case is to increase privacy and reduce latency by
selecting one or possibly even more instances to use.
