### ISSUE TITLE
Only Errors since 1.2.5

### ISSUE THREAD

**Issue by AlphaElwedritsch** [yaxarat/lingvaandroid#32]
Since last update (1.2.5) I get only errors, whatever I#m trying to do.
Cannot change any setting. First screenshot
Cannot Translate. Second Screenshot

Using iodèOS (LOS 19.1 based)

![Screenshot_20221026-093122_Lentil Translate-1](https://user-images.githubusercontent.com/109347938/197963353-1f788a9f-90b1-4757-9744-2f0991ceabb5.png)
![Screenshot_20221026-093153_Lentil Translate-2](https://user-images.githubusercontent.com/109347938/197963373-5a72463c-b7f4-4186-84ef-8156638be833.png)

**Comment by yaxarat** [comment]
A hot fix is already released. Please try updating to version 1.2.6. Fdroid seems to [take a long time](https://forum.f-droid.org/t/how-long-for-an-app-to-be-available-for-download-once-metadata-are-updated/12740) from when a fix is published to actually updating the listing, so a quick work around would be to get it directly from the Playstore.
