### ISSUE TITLE
Continuous deletion in text area isn't smooth

### ISSUE THREAD

**Issue by faustaahmad** [yaxarat/lingvaandroid#33]
Hold backspace button to trigger continuous deletion

- **GBoard** 11.0.13
It's quite hard to use continuous deletion, sometimes stuck & need to hold backspace again
- **Samsung Keyboard & FlorisBoard**
Just for comparsion
continuous deletion works with this keyboard, but animation in text area isn't smooth

**Comment by yaxarat** [comment]
@faustaahmad Can you share a screen recording? I am having trouble reproducing the issue.

**Comment by faustaahmad** [comment]
@yaxarat hope this help, I'm holding backspace button
- Gboard 12.3.04 (latest)
https://void.cat/Domh1qUoiaHwDptZeGPmCK
- FlorisBoard, Gboard 11.0.13, Samsung Keyboard
https://void.cat/UJ8AABWAbreSyN1mymMWfa

**Comment by yaxarat** [comment]
Thanks! I will take a look for the next release. I also see there is some cutout issue at the top, will look to fix that as well 😬
