### ISSUE TITLE
Feature request: specify custom Lingva server address

### ISSUE THREAD

**Issue by whereismybugfix** [yaxarat/lingvaandroid#35]
First of all, thank you for the app. I really like it 🙌

As the title says, I've got an idea of having a field for a custom Lingva instance address in the settings, so that if I host my own server, I can make sure that the app is using it.

I see you are currently using fixed list of instances to get translations here: https://github.com/yaxarat/lingvaandroid/blob/main/app/src/main/java/dev/atajan/lingva_android/api/LingvaApi.kt#L20

Maybe some tinkering around that part of functionality could do the trick.

**Comment by yaxarat** [comment]
Thank you for the feedback! I will take a look at this feature request for the next release. On a personal note, I'm at bit of a rough patch in my personal life right now and have not been able to put the attention I want on this (or any other to be fair) project. So it might take few weeks, but I will definitely get to this.

**Comment by parasiteoflife** [comment]
Hi, has this feature not been released yet? Currently I only see the theme and default language options.
Thank you.
