### ISSUE TITLE
Theme selection resets on app start

### ISSUE THREAD

**Issue by Kalastelija123** [yaxarat/lingvaandroid#37]
The app theme selection radio button reverts back to "YOU - Based on your device wallpaper and theme" each time the app is started. The theme itself is not reset; if I have previously set my theme to "Dark", the colors are applied correctly, but the selection still shows the "YOU"-option.

**Comment by yaxarat** [comment]
Nice spot! I will iron this bug out for the next release.

**Comment by yaxarat** [comment]
Fixed in https://github.com/yaxarat/lingvaandroid/pull/39
