### ISSUE TITLE
FDroid Specific issue: Unable to load the new version 1.3.0 (it crashes/freezes on the start) 

### ISSUE THREAD

**Issue by Moostek** [yaxarat/lingvaandroid#48]
Hello, with the new update v1.3.0 the app freezes, I can not start it up. I have LineageOS 16.0. I returned to the previous version v1.2.6, and this one works fine. 

Can you examine this and fix it up, please? 
Thank you.

**Comment by JohanvdS** [comment]
Same tot me on vollaphone app crashed

**Comment by yaxarat** [comment]
I will look into this asap. Thank you for the report!

**Comment by Komprogue** [comment]
Confirm, latest version just crashes at start.

**Comment by yaxarat** [comment]
Are all of the crash from the FDroid installs? I am having problem replicating the crash.

**Comment by Moostek** [comment]
Yes, mine Lentil app I installed via F-Droid.

**Comment by Komprogue** [comment]
> Are all of the crash from the FDroid installs? I am having problem replicating the crash.

Yes, it's from last f-droid update.

**Comment by yaxarat** [comment]
I am still investigating this issue. I can't seem to reproduce it from either Playstore or Fdroid versions. 
It would be a big help if anyone experiencing the crash could try out the Playstore version and see if the crash occurs.

Maybe it's an android version-related bug.

**Comment by yaxarat** [comment]
I was able to repro it and it should be fixed in the next release, which is rolling out as we speak. Thank you all for the report!
