### ISSUE TITLE
on the vollaphone  

### ISSUE THREAD

**Issue by JohanvdS** [yaxarat/lingvaandroid#55]
I am not able to use the translation because it gets blocked with a failure. Screen uh oh :( try again later. Did that for a couple day's so now I Try You 🤔🤣 hope this works

**Comment by yaxarat** [comment]
Can you double check this text field is empty? Does the issue still occur after uninstall/re-install of the app?
<img width="450" alt="Screenshot 2023-07-30 at 11 47 57 AM" src="https://github.com/yaxarat/lingvaandroid/assets/27980758/15c9b46c-89dc-4860-8b57-1533fc173d27">

**Comment by JohanvdS** [comment]
Hi,

I uninstalled and reinstalled but it still gives failures but after I did reboot the phone the problem was gone.

Thanks

Johan
--
Johan van de Sande
De mattein 66
1790 Hekelgem
België

+32471 111 369 



30 jul. 2023 17:49 van ***@***.***:
