### ISSUE TITLE
Default Lingva instance is no longer accessible

### ISSUE THREAD

**Issue by lokesh-krishna** [yaxarat/lingvaandroid#56]
The default Lingva instance (lingva.ml) is down, along with others hosted on `.ml` domains. This was addressed by the project here: [#76](https://github.com/translate-tools/core/issues/76).

We too could maybe make `translate.plausibility.cloud` the default instance?

**Comment by yaxarat** [comment]
Fixed in https://github.com/yaxarat/lingvaandroid/pull/57
